INSERT INTO tb_game_list (name) VALUES ('Aventura e RPG');
INSERT INTO tb_game_list (name) VALUES ('Jogos de plataforma');

INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Digimon World 4', 4.8, 2005, 'RPG eletrônico de ação, Jogo eletrônico de aventura', 'Nintendo GameCube, PlayStation 2, Xbox', 'https://i0.wp.com/www.finalfaqs.com.br/wp-content/uploads/2021/12/Digimon-World-4.jpg?w=1280&ssl=1', 'Digimon World 4, conhecido como Digimon World X no Japão, é um videogame RPG de ação para PlayStation 2, GameCube e Xbox desenvolvido pela BEC e publicado pela Bandai como parte de sua franquia Digimon.', 'Digimon World 4 , conhecido como Digimon World X no Japão, é um RPG de ação para PlayStation 2 , GameCube e Xbox desenvolvido pela BEC e publicado pela Bandai como parte de seu Digimon . franquia. Ao contrário dos jogos anteriores da série Digimon World , apresenta hack and slash baseado em açãojogabilidade e suporta até quatro jogadores. Cada jogador joga como um Agumon, um Veemon, um Guilmon e um Dorumon. O jogo é vagamente baseado no filme Digital Monster X-Evolution de 2005 , mesmo usando imagens do próprio filme. A versão GameCube não foi lançada na região PAL .');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Final Fantasy XII: The Zodiac Age', 4.9, 2017, 'RPG eletrônico, Jogo eletrônico de aventura', ' Nintendo Switch, PlayStation 4, Xbox One, Microsoft Windows', 'https://cf.shopee.com.br/file/c69045dbe7d4f3a2ab82da43d1f8d979', 'Final Fantasy XII é um jogo eletrônico de RPG desenvolvido e publicado pela Square Enix exclusivamente para o PlayStation 2, sendo o décimo segundo título principal da série Final Fantasy.', 'Final Fantasy XII é um jogo eletrônico de RPG desenvolvido e publicado pela Square Enix exclusivamente para o PlayStation 2, sendo o décimo segundo título principal da série Final Fantasy. O jogo apresentou várias inovações como um novo sistema de batalha, câmera controlável, um sistema que permitia que os jogadores controlassem as ações de outros personagens e outro em que determinava quais habilidades e equipamentos seriam utilizados. Final Fantasy XII também inclui diversos elementos recorrentes da franquia, como monstro convocáveis e chocobos.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('The Witcher 3: Wild Hunt', 4.7, 2014, 'RPG Eletronico, Aventura', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/3.png', 'Ambientado em um gigantesco cenário medieval que dá liberdade total ao jogador, o game, que possui uma jogabilidade não linear e é jogado através de uma perspectiva em terceira pessoa, tem o lendário bruxo Geralt de Rívia como seu protagonista, o qual inicia uma longa jornada pelos Reinos do Norte.', 'Ambientado em um gigantesco cenário medieval que dá liberdade total ao jogador, o game, que possui uma jogabilidade não linear e é jogado através de uma perspectiva em terceira pessoa, tem o lendário bruxo Geralt de Rívia como seu protagonista, o qual inicia uma longa jornada pelos Reinos do Norte. Enquanto a ordem planetária enfrenta uma grande mudança, com o misterioso e macabro exército de cavaleiros vermelhos conhecido como a "Caçada Selvagem" deixando somente sangue e ruína por onde passa, o jogador terá de enfrentar diversos perigos, usando espadas e magia num mundo em crise, à medida que interage com outros personagens e completa missões para o progresso da história, podendo viajar a pé, a barco, ou montado em Carpeado, o cavalo inseparável de Geralt.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Sekiro: Shadows Die Twice', 3.8, 2019, 'RPG Eletronico, Aventura', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/4.png', 'A jogabilidade é focada em furtividade, exploração e combate, com ênfase especial em batalhas contra chefes. Embora a maior parte do jogo ocorra em áreas fictícias, algumas áreas são fortemente inspiradas em edifícios e locais do mundo real no Japão.', 'A jogabilidade é focada em furtividade, exploração e combate, com ênfase especial em batalhas contra chefes. Embora a maior parte do jogo ocorra em áreas fictícias, algumas áreas são fortemente inspiradas em edifícios e locais do mundo real no Japão. O jogo também faz fortes referências à mitologia e filosofia budista. Enquanto criava o jogo, o diretor Hidetaka Miyazaki queria criar uma nova propriedade intelectual (IP) que marcasse um ponto de partida da série de jogos Souls, também feita pela FromSoftware, e buscou inspiração em séries como Tenchu.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Ghost of Tsushima', 4.6, 2012, 'RPG Eletronico, Aventura', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/5.png', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. A história acompanha Jin Sakai, um samurai que precisa proteger a Ilha de Tsushima durante a primeira invasão mongol do Japão. ', 'Ghost of Tsushima é um jogo eletrônico de ação-aventura desenvolvido pela Sucker Punch Productions e publicado pela Sony Interactive Entertainment. A história acompanha Jin Sakai, um samurai que precisa proteger a Ilha de Tsushima durante a primeira invasão mongol do Japão. Ele se vê dividido entre escolher seguir o código do guerreiro para lutar honradamente ou usar métodos práticos e desonrosos para subjugar os mongóis.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Super Mario World', 4.7, 1990, 'Eletronico de Plataforma', 'Super Ness, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/6.png', 'Super Mario World é frequentemente considerado um dos melhores jogos da série Mario, e citado como um dos melhores jogos eletrônicos já feitos. É o jogo mais vendido do SNES e um dos jogos mais vendidos de todos os tempos, com mais de vinte milhões de unidades comercializadas em todo o mundo.', 'Super Mario World é frequentemente considerado um dos melhores jogos da série Mario, e citado como um dos melhores jogos eletrônicos já feitos. É o jogo mais vendido do SNES e um dos jogos mais vendidos de todos os tempos, com mais de vinte milhões de unidades comercializadas em todo o mundo. Seu sucesso levou a uma série de televisão animada com o mesmo nome e uma prequela, Yoshis Island, lançada inicialmente em agosto de 1995.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Hollow Knight', 4.6, 2017, 'Eletronico de Plataforma', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/7.png', 'Hollow Knight é um jogo indie de gênero metroidvania desenvolvido e publicado pela Team Cherry, lançado para Microsoft Windows, macOS e Linux em 2017 e, posteriormente, para Nintendo Switch, Playstation 4 e Xbox One em 2018.', 'O jogo começa com o personagem principal, O Cavaleiro, entrando nas ruínas de Hallownest, um reino que era habitado por insetos antropomórficos, e vai descobrindo, conforme dialoga com os personagens e explora Hallownest, que ele é um dos receptáculos criados para selar uma entidade divina chamada Radiância que a muito tempo era idolatrada, até a chegada do Rei Pálido, que deu sapiência aos insetos de Hallownest e, em turno, fez eles esquecerem da Radiância e o idolatrarem em vez disso. A Radiância foi o que causou a ruína de Hallownest; ela não possui um corpo físico, mas ela consegue invadir a mente dos insetos, levando-os à loucura e assim criando "A Infecção".');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Ori and the Blind Forest', 4, 2015, 'Eletronico de Plataforma', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/8.png', 'Ori and the Blind Forest é um Jogo de plataforma em 2D. O jogador controla Ori, um espírito branco guardião de gênero indeterminado, e Sein, que é a luz e os olhos do Espírito da Árvore.', 'Ori and the Blind Forest é um Jogo de plataforma em 2D. O jogador controla Ori, um espírito branco guardião de gênero indeterminado, e Sein, que é a luz e os olhos do Espírito da Árvore.[1] Ori pode pular, escalar e usar outras habilidades para se locomover. Sein pode atirar Chamas de Espírito para combater inimigos e quebrar obstáculos.');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Cuphead', 4.6, 2017, 'Eletronico de Plataforma', 'XBox, Playstation, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/9.png', 'Além dos gráficos extremamente detalhistas e fiéis aos cartoons da Era de Ouro da animação americana, o jogo chama a atenção pela particularidade, lembrando os jogos de plataforma dos anos 90 em 8 e 16 bit.', 'Além dos gráficos extremamente detalhistas e fiéis aos cartoons da Era de Ouro da animação americana, o jogo chama a atenção pela particularidade, lembrando os jogos de plataforma dos anos 90 em 8 e 16 bit. É possível perceber referências a alguns desses jogos, como Contra, Mega Man X, Gunstar Heroes, Street Fighter III e Thunderforce (quando das fases aéreas).');
INSERT INTO tb_game (titulo, nota, ano, genero, plataforma, img_url, descricao_curta, descricao_longa) VALUES ('Sonic CD', 4, 1993, 'Eletronico de Plataforma', 'Sega CD, PC', 'https://raw.githubusercontent.com/devsuperior/java-spring-dslist/main/resources/10.png', 'A jogabilidade é praticamente idêntica a dos jogos anteriores, e apenas o ato 3 se passa no tempo futuro, que pode ser do bem ou do mal. ', 'A jogabilidade é praticamente idêntica a dos jogos anteriores, e apenas o ato 3 se passa no tempo futuro, que pode ser do bem ou do mal. Para que o futuro seja do bem, Sonic deve voltar ao passado nos atos 1 e 2, por meio das placas com a inscrição "Past", tomando velozes impulsos, ou conseguindo obter todas as TIME STONES.')

INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 1, 0);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 2, 1);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 3, 2);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 4, 3);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (1, 5, 4);

INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 6, 0);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 7, 1);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 8, 2);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 9, 3);
INSERT INTO tb_belonging (list_id, game_id, posicao) VALUES (2, 10, 4);